language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install git libmicrohttpd-dev libcurl4-openssl-dev libjsoncpp-dev libjsonrpccpp-dev libjsonrpccpp-tools libargtable2-dev libhiredis-dev
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - export CXX="g++-4.8"
  - cd ../../bitcoin-api-cpp

before_script:
  - mkdir -p build
  - cd build
  - cmake ..

script:
  - make -j8

